#!/usr/bin/env zsh

# Add changes to git.
git add .

# Commit changes.
msg="kemas kini secara pukal"
if [ $# -eq 1 ]
  then msg="$1"
fi
git commit -m "$msg"

# Push source and build repos.
git push -u origin main
