#!/usr/bin/env zsh

conversion_dir="gm"
mkdir -p $conversion_dir
cd $conversion_dir

for SVG in ../*.svg; do
  gm convert "$SVG" "$(basename "$SVG" .svg).png";
done

# https://superuser.com/a/444959
gm convert output7.png -matte -operator Opacity Assign 60% compose4.png

# http://www.graphicsmagick.org/composite.html
# http://www.graphicsmagick.org/GraphicsMagick.html#details-compose
gm composite compose4.png output6.png -compose Multiply compose5.png
gm composite compose5.png output5.png -compose Multiply compose6.png
