#!/usr/bin/env zsh

conversion_dir="gm"
mkdir -p $conversion_dir
cd $conversion_dir

for SVG in ../*.svg; do
  gm convert "$SVG" "$(basename "$SVG" .svg).png";
done

#gm help command [options ...]
gm convert output8.png -matte -operator Opacity Assign 60% compose1.png

gm composite compose1.png output7.png -compose Multiply compose2.png
gm composite compose2.png output6.png -compose Multiply compose3.png
