#!/usr/bin/env zsh

conversion_dir="im"
mkdir -p $conversion_dir
cd $conversion_dir

for SVG in ../*.svg; do
  convert "$SVG" "$(basename "$SVG" .svg).png";
done

# https://superuser.com/q/444585
# https://imagemagick.org/script/command-line-options.php#alpha
#convert -list <options> (untuk dapatkan senarai operator)
convert output7.png -alpha Set -channel A -evaluate Set 40% compose1.png

# https://imagemagick.org/script/composite.php 
#composite output6.png output5.png -compose Multiply compose3.png

composite compose1.png output6.png -compose Multiply compose2.png
composite compose2.png output5.png -compose Multiply compose3.png
